'================ START OF SCRIPT ==================='.

'mnesia:start()'.
 mnesia:start().

'gen_server:start({global, assets}, assets, [], [{debug,[trace]}] )'.
 gen_server:start({global, assets}, assets, [], [ ] ).

'gen_server:start({global, services}, services, [], [{debug,[trace]}] )'.
 gen_server:start({global, services}, services, [], [ ] ).

'gen_server:start({global, transformers}, transformers, [], [{debug,[trace]}] )'.
 gen_server:start({global, transformers}, transformers, [], [ ] ).

'gen_server:start({global, circuits}, circuits, [], [{debug,[trace]}] )'.
 gen_server:start({global, circuits}, circuits, [], [ ] ).

'global:registered_names()'.
 global:registered_names().

'circuits:test()'.
 circuits:test().
 
'mnesia:info()'.
 mnesia:info().

'mnesia:stop()'.
 mnesia:stop().

'q()'.
 q().

'================ END OF TEST ==================='.
