'================ START OF TEST ==================='.

'gen_server:start({global, assets}, assets, [], [{debug,[trace]}] )'.
 gen_server:start({global, assets}, assets, [], [ ] ).

'gen_server:start({global, services}, services, [], [{debug,[trace]}] )'.
 gen_server:start({global, services}, services, [], [ ] ).

'gen_server:start({global, transformers}, transformers, [], [{debug,[trace]}] )'.
 gen_server:start({global, transformers}, transformers, [], [{debug,[trace]}] ).

'gen_server:start({global, circuits}, circuits, [], [{debug,[trace]}] )'.
 gen_server:start({global, circuits}, circuits, [], [{debug,[trace]}] ).

'global:registered_names()'.
 global:registered_names().

'meters:test()'.
 meters:test().

'ets:tab2list( circuit_usage )'.
 ets:tab2list( circuit_usage ).

'ets:tab2file( assets, "assets_table" )'.
 ets:tab2file( assets, "assets_table" ).

'ets:tab2file( service_usage, "service_usage_table" )'.
 ets:tab2file( service_usage, "service_usage_table" ).

'ets:tab2file( transformer_usage, "transformer_usage_table" )'.
 ets:tab2file( transformer_usage, "transformer_usage_table" ).

'ets:tab2file( circuit_usage, "circuit_usage_table" )'.
 ets:tab2file( circuit_usage, "circuit_usage_table" ).

'q()'.
 q().

'================ END OF TEST ==================='.
