'================== START SCRIPT ================='.
'================ START OF TEST ==================='.
'gen_server:start({global, assets}, assets, [], [{debug,[trace]}] )'.
 gen_server:start({global, assets}, assets, [], [] ).

'gen_server:start({global, services}, services, [], [{debug,[trace]}] )'.
 gen_server:start({global, services}, services, [], [ ] ).

'gen_server:start({global, transformers}, transformers, [], [{debug,[trace]}] )'.
 gen_server:start({global, transformers}, transformers, [], [ ] ).

'gen_server:start({global, circuits}, circuits, [], [{debug,[trace]}] )'.
 gen_server:start({global, circuits}, circuits, [], [ ] ).

'global:registered_names()'.
 global:registered_names().


'simulator:simulate_month_test()'.
 simulator:simulate_month_test().

'ets:tab2file( assets, "assets_table" )'.
 ets:tab2file( assets, "assets_table" ).

'ets:tab2file( service_series, "service_series_table" )'.
 ets:tab2file( service_series, "service_series_table" ).

'ets:tab2file( transformer_series, "transformer_series_table" )'.
 ets:tab2file( transformer_series, "transformer_series_table" ).

'ets:tab2file( circuit_series, "circuit_series_table" )'.
 ets:tab2file( circuit_series, "circuit_series_table" ).




'q()'.
 q().
'================== END SCRIPT ================='.
