'=================== START OF SCRIPT ======================'.

'net_adm:ping( messengerNode@RichardGreenMacBookPro.local )'.
 net_adm:ping( messengerNode@RichardGreenMacBookPro.local ).

'net_adm:ping( quadNode@RichardGreenMacBookPro.local )'.
 net_adm:ping( quadNode@RichardGreenMacBookPro.local ). 

'timer:sleep( 4000 )'.
 timer:sleep( 4000 ).

'global:registered_names()'.
 global:registered_names().

'messenger:is_running()'.
 messenger:is_running().

'application:start( mdm2 )'.
 application:start( mdm2 ).

'sim_install:test()'.
 sim_install:test().

'timer:sleep( 4000 )'.
 timer:sleep( 4000 ).

'application:stop( mdm2 )'.
 application:stop( mdm2 ).

'global:registered_names()'.
 global:registered_names().

'quad:quad()'.
 quad:quad().

'quad:quad() ! flush'.
 quad:quad() ! flush.

'=================== END OF SCRIPT ======================'.

