'================== START SCRIPT ================='.

'mnesia:start()'.
 mnesia:start().

'gen_server:start({global, assets}, assets, [], [{debug,[trace]}] )'.
 gen_server:start({global, assets}, assets, [], [] ).

'gen_server:start({global, services}, services, [], [{debug,[trace]}] )'.
 gen_server:start({global, services}, services, [], [ ] ).

'gen_server:start({global, transformers}, transformers, [], [{debug,[trace]}] )'.
 gen_server:start({global, transformers}, transformers, [], [ ] ).

'gen_server:start({global, circuits}, circuits, [], [{debug,[trace]}] )'.
 gen_server:start({global, circuits}, circuits, [], [ ] ).

'mnesia:clear_table( object )'.
 mnesia:clear_table( object ).

'mnesia:clear_table( service_series )'.
 mnesia:clear_table( service_series ).

'mnesia:clear_table( transformer_series )'.
 mnesia:clear_table( transformer_series ).

'mnesia:clear_table( circuit_series )'.
 mnesia:clear_table( circuit_series ).


'mnesia:info()'.
 mnesia:info().

'global:registered_names()'.
 global:registered_names().

'simulator:month_load_tester()'.
 simulator:month_load_tester().

'mnesia:info()'.
 mnesia:info().

'mnesia:stop()'.
 mnesia:stop().

'q()'.
 q().
'================== END SCRIPT ================='.
